### ISSUE TITLE
Digdag consistently takes 20% of the CPU

### ISSUE THREAD

**Issue by brianhks** [treasure-data/digdag#648] opened 2017-09-22 01:20 UTC
All I'm running is a simple test that echos out some values once a minute.  Have a look at the cpu graph I turned digdag off at 19:16

![digdag_cpu](https://user-images.githubusercontent.com/2686690/30725403-d75060a2-9f01-11e7-9634-0503f7f8b79c.png)

**Comment by brianhks** [comment] 2017-09-22 01:20
This is with the latest 9.16 version.

**Comment by hiroyuki-sato** [comment] 2017-09-22 12:47
Hello, @brianhks 

Could you tell me more detail about your test environment?

* Mode: server /scheduler?
* DB Connection: PostgreSQL / H2?
* PostgreSQL connect to another server or same server?
* dig file


I roughly checked CPU usage with an in-memory database.
It doesn't use CPU much.

Please see detail.
https://github.com/hiroyuki-sato/digdag-support/tree/master/core_648_cpu_usage

**Comment by brianhks** [comment] 2017-09-22 12:50
I have a server running and this is my dig file
`timezone: UTC

schedule:
  minutes_interval>: 1

+setup:
  echo>: start ${session_time}

+disp_current_date:
  echo>: ${moment(session_time).utc().format('YYYY-MM-DD HH:mm:ss Z')}

+teardown:
  echo>: finish ${session_time}
`

I'm using the H2 database.

**Comment by hiroyuki-sato** [comment] 2017-09-22 12:56
What OS and Java are you using? 
My similar test case always 93~95% idle. (Please see the previous post).

**Comment by brianhks** [comment] 2017-09-22 15:56
OS is Ubuntu: Linux vm-server 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Java is: java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

now it is only 20% of one core but still, between running the job it should be doing nothing which it is obviously not as it is doing something.  Have you guys attached a profile to see what it is doing when it isn't supposed to be doing anything?

**Comment by brianhks** [comment] 2017-09-22 16:10
Even in your test it takes between 40-60% of your cpu just to do an echo task.  That seems way too much.

**Comment by hiroyuki-sato** [comment] 2017-09-25 10:34
I'm not sure root cause but, there are two problems.

1. The echo> task takes 40~60% of the CPU. 
2. Digdag consistency takes 20% of the CPU (idle time).

I reproduced first one, but I can't reproduce 2nd one. 

As far as I know, digdag store task execution result into a database after `echo>` operator finished. 
It may use much CPU resource. It needs more investigation.

Do you have any information about case 2?

**Comment by yoyama** [comment] 2019-07-12 06:37
@brianhks I will close this issue because Digdag version is old to confirm it. Feel free to reopen or recreate issue if you need.

**Closed by yoyama** 2019-07-12 06:37 UTC
