### ISSUE TITLE
Failed to process variables. caused by: spurious LambdaForm ClassCastException

### ISSUE THREAD

**Issue by daydream772** [treasure-data/digdag#1443] opened 2020-08-12 10:38 UTC
It worked fine but today all jobs are failure with the same error. I refer to https://github.com/treasure-data/digdag/issues/391. Tried to build the image with different kind of:

- OpenJDK version 
8u162
8u212
8u262
- Digdag version
0.9.41
0.9.42 

But still got same error message like 
`2020-08-12 10:23:16.285 +0000 [ERROR] (0069@+run) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: Failed to process variables
java.lang.RuntimeException: Failed to process variables
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:204)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.invoke.LambdaForm cannot be cast to [Ljava.lang.invoke.LambdaFormEditor$Transform;
	at java.lang.invoke.LambdaFormEditor.getInCache(LambdaFormEditor.java:275)
	at java.lang.invoke.LambdaFormEditor.filterArgumentForm(LambdaFormEditor.java:635)
	at java.lang.invoke.MethodHandles.filterArgument(MethodHandles.java:2623)
	at java.lang.invoke.MethodHandles.filterArguments(MethodHandles.java:2611)
	at jdk.nashorn.internal.lookup.MethodHandleFactory$StandardMethodHandleFunctionality.filterArguments(MethodHandleFactory.java:383)
	at jdk.nashorn.internal.runtime.WithObject.filterReceiver(WithObject.java:324)
	at jdk.nashorn.internal.runtime.WithObject.fixScopeCallSite(WithObject.java:300)
	at jdk.nashorn.internal.runtime.WithObject.lookup(WithObject.java:132)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$21136$13$\^function\_.L:1(<function>:4)
	at jdk.nashorn.internal.scripts.Script$Recompilation$21120$62AA$\^eval\_.template(<eval>:53)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:641)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.digdag.core.agent.ConfigEvalEngine.invokeTemplate(ConfigEvalEngine.java:112)
	at io.digdag.core.agent.ConfigEvalEngine.access$200(ConfigEvalEngine.java:30)
	at io.digdag.core.agent.ConfigEvalEngine$Context.evalValue(ConfigEvalEngine.java:206)
	at io.digdag.core.agent.ConfigEvalEngine$Context.evalObjectRecursive(ConfigEvalEngine.java:164)
	at io.digdag.core.agent.ConfigEvalEngine$Context.access$000(ConfigEvalEngine.java:132)
	at io.digdag.core.agent.ConfigEvalEngine.eval(ConfigEvalEngine.java:78)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:195)
	... 10 common frames omitted`

*I use postgresql 9.6.

**Comment by hiroyuki-sato** [comment] 2020-08-13 04:31
Hello, @daydream772 
It seems that this error relates to JavaScript`${}`. Could you double-check your configuration? (Could you show  us your configuration?)

**Comment by daydream772** [comment] 2020-08-13 05:42
@hiroyuki-sato thanks for your replying.
I'm not sure what do you mean about configuration. 
For my work, 

1. Build [Dockerfile.txt](https://github.com/treasure-data/digdag/files/5067278/Dockerfile.txt)
2. Launch this image with postgresql([config.txt](https://github.com/treasure-data/digdag/files/5067286/config.txt))
3. Other properties - [properties.txt](https://github.com/treasure-data/digdag/files/5067292/properties.txt)

I didn't see any setting for JavaScript. Could you give me more hints? Thank you.

**Comment by hiroyuki-sato** [comment] 2020-08-13 07:32
Hello, @daydream772 

JavaScript means that you are using `${}` syntax in `.dig` file.
Because of the attached log showing `Nashorn` keywords. Nashorn is the JavaScript engine in Java.

When did this error happen? (ex. starting digdag  execute `digdag start`)
Have you ever tried to launch without Docker?

**Comment by daydream772** [comment] 2020-08-13 08:25
Hi @hiroyuki-sato 
It just happened suddenly. 
We have 2 separate Digdag server running on Docker of Google Compute Engine that have been running for a long time. 
One of them happened last week and the other one happened yesterday(same error). 

But I got a dev Digdag without posgresql and it works fine. Maybe something wrong and might be written into DB? (But we only use "date" and "int" type of value)

**Comment by hiroyuki-sato** [comment] 2020-08-13 11:50
Hello, @daydream772 

I've never heard this error. Does this error reports at `digdag start`?
Have you ever tried `digdag server -l debug` option?

**Comment by daydream772** [comment] 2020-08-14 03:54
Hi @hiroyuki-sato 

I only saw this error in https://github.com/treasure-data/digdag/issues/391. But it looks like didn't solve. 
Usually, I monitor workflows in the console of digdag server. This time I tried `digdag start` to launch a workflow. And I use `digdag task` and `digdag log` to get the output. I think there's some new clue in `digdag task`.

`digdag task`
`error: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of io.digdag.client.api.ImmutableRestTask, problem: Cannot build RestTask, some of required attributes are not set [error]
 at [Source: (org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper); line: 1, column: 306] (through reference chain: io.digdag.client.api.ImmutableRestTaskCollection$Json["tasks"]->java.util.ArrayList[0]) (processing)`

`digdag log`
`2020-08-14 02:35:08.260 +0000 [ERROR] (0078@[0:testdag]+testdag) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: Failed to process variables
java.lang.RuntimeException: Failed to process variables
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:204)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.invoke.LambdaForm cannot be cast to [Ljava.lang.invoke.LambdaFormEditor$Transform;
	at java.lang.invoke.LambdaFormEditor.getInCache(LambdaFormEditor.java:275)
	at java.lang.invoke.LambdaFormEditor.filterArgumentForm(LambdaFormEditor.java:635)
	at java.lang.invoke.MethodHandles.filterArgument(MethodHandles.java:2623)
	at java.lang.invoke.MethodHandles.filterArguments(MethodHandles.java:2611)
	at jdk.nashorn.internal.lookup.MethodHandleFactory$StandardMethodHandleFunctionality.filterArguments(MethodHandleFactory.java:383)
	at jdk.nashorn.internal.runtime.WithObject.filterReceiver(WithObject.java:324)
	at jdk.nashorn.internal.runtime.WithObject.fixScopeCallSite(WithObject.java:300)
	at jdk.nashorn.internal.runtime.WithObject.lookup(WithObject.java:132)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$144923$13$\^function\_.L:1(<function>:3)
	at jdk.nashorn.internal.scripts.Script$Recompilation$144920$62AA$\^eval\_.template(<eval>:53)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:641)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at io.digdag.core.agent.ConfigEvalEngine.invokeTemplate(ConfigEvalEngine.java:112)
	at io.digdag.core.agent.ConfigEvalEngine.access$200(ConfigEvalEngine.java:30)
	at io.digdag.core.agent.ConfigEvalEngine$Context.evalValue(ConfigEvalEngine.java:206)
	at io.digdag.core.agent.ConfigEvalEngine$Context.evalObjectRecursive(ConfigEvalEngine.java:164)
	at io.digdag.core.agent.ConfigEvalEngine$Context.access$000(ConfigEvalEngine.java:132)
	at io.digdag.core.agent.ConfigEvalEngine.eval(ConfigEvalEngine.java:78)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:195)
	... 10 common frames omitted`

We use debug mode already but no clue in there.

**Comment by hiroyuki-sato** [comment] 2020-08-14 06:02
Hello, @daydream772 

If I get the same situation, I'll try this. I have no idea how to fix this error.

* Dump `digdag` database using `pgdump`.
* Create another database for testing.
* Load dump data into new database.
* try to connect `digdag` server.

**Comment by daydream772** [comment] 2020-08-14 10:33
Hi @hiroyuki-sato 

Once I find the root cause I'll update in here. Thanks for your help.

**Comment by toru-takahashi** [comment] 2020-08-14 15:03
Hello,

Thank you for your report.
We had experienced #391 before. Even though the error is a bit different, I guess they are a similar root cause.
Because the error indicates `java.lang.Thread.run(Thread.java:748) Caused by: java.lang.ClassCastException: java.lang.invoke.LambdaForm cannot be cast to [Ljava.lang.invoke.LambdaFormEditor$Transform; at`

They are essentially a bug of Nashborn Javascript Engine

- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8154236
- https://bugs.openjdk.java.net/browse/JDK-8145371

In order to resolve #391, we decided not to fix for Nashborn since Nashborn will be deprecated after Java11.
We have released introduce Graal JavaScript engine and start to support Java 11 from digdag v0.10
https://github.com/treasure-data/digdag/pull/1256

We Treasure Data have used digdag v0.10 with Java11 and this type of issues don't happen.
https://github.com/treasure-data/digdag/tree/v0_10

If the issue happens, you may need to consider using digdag v0.10 with Java11.

Thank you,

**Comment by daydream772** [comment] 2020-08-18 09:08
Hi @toru-takahashi  thanks for your replying.

I tried Digdag v0.10 with Java11 with a new postgresql DB, it works fine. But when I point it to the origin postgresql DB it shows same issue. Maybe something wrong in the DB. I'll keep looking at what's happened in the DB. At least, we have a working one. 

Thank you for all your support.

**Comment by yoyama** [comment] 2020-12-10 08:15
The Issue has been resolved. Close.

**Closed by yoyama** 2020-12-10 08:15 UTC
Labels: question
